# Generated by Django 5.0.4 on 2024-05-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms_project', '0005_auto_20190814_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
